apiVersion: v1
kind: Service
metadata:
  name: video-streaming-app
spec:
  selector:
    app: video-streaming-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

